INSERT INTO PATENT (patent_application_number, archive_uri,
                    assignee_entity_name,
                    assignee_postal_address_text,
                    downloaded_status,
                    file_location_uri,
                    filing_date,
                    inserted_on,
                    invention_subject_matter_category,
                    invention_title, inventor_names,
                    main_cpcs_symbol_text,
                    processed_status,
                    publication_date,
                    publication_document_identifier,
                    updated_on)
VALUES ('US13247589',
        'https://bulkdata.uspto.gov/data/patent/application/redbook/bibliographic/2012/ipab20120119_wk03.zip',
        'QUALCOMM', 'San Diego', 'P',
        'https://dh-opendata.s3.amazonaws.com/publication_pdf/app_pdf_20120119/2012-03/US/2012/0014/428/A1/US20120014428A1.pdf',
        current_date, current_date, 'Semicondutor utility', 'METHODS AND SYSTEMS FOR INITIAL FCH PROCESSING',
        'TEST TEST', null,'P', null, 'US20120014428A1', null);